version: "3.8"

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: blossomdevs/line-up-server:main
    ports:
      - "8080:8080"

  redis:
    build:
      context: ./docker-files
      dockerfile: redis
    image: blossomdevs/line-up-server:redis
    ports:
      - "6379:6379"

  nginx:
    build:
      context: ./docker-files
      dockerfile: nginx
    image: blossomdevs/line-up-server:nginx
    ports:
      - "80:80"
