jwt:
  secret: ${JWT_SECRET}
  access-expiration: 1800000 #30분
  access-header: Authorization

  refresh-expiration: 604800000 #1주일
  refresh-setCookie: refreshToken

  cookie-expiration: 604800000  #1주일

