cloud:
  aws:
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME}
    credentials:
      accessKey: ${AWS_S3_BUCKET_ACCESS_KEY}
      secretKey: ${AWS_S3_BUCKET_SECRET_KEY}
    region:
      static: ap-northeast-2
    # stack.auto를 false로 지정하지 않으면 StackTrace가 발생한다.
    stack:
      auto: false