spring:
  profiles:
    active:
      - prod
    group:
      local:
        - local
      prod:
        - prod
      ci:
        - ci
    include:
      - redis
      - jwt
      - oauth
      - s3
      - env
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      resolve-lazily: true
      max-file-size: 5MB     # 파일의 용량 제한
      max-request-size: 10MB # 전체 최대 크기 용량 제한
