jwt:
  secret: TMKMhLAYiR7ipWkTFw7bJujt8uFzuh83b21gx9Dteljut8
  #set token expiration period in minutes
  access:
    expiration: 30 #30분
    header: Authorization

  refresh:
    expiration: 20160 #2주일
    set_cookie: refreshToken

  cookie:
    expiration: 10080 #1주일

