spring:
  profiles:
    active:
      - prod
    group:
      local:
        - local
      prod:
        - prod
    include:
      - kafka
      - redis
      - jwt
      - env
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

