name: Deploy docker image to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.AWS_ECR_NAME }}
          TAG1: ${{ secrets.AWS_ECR_TAG1 }}
          TAG2: ${{ secrets.AWS_ECR_TAG2 }}
        run: |
          docker-compose build
          docker-compose push

      - name: Generate Dockerrun.aws.json
        run: |
          echo '{"AWSEBDockerrunVersion": "2", "containerDefinitions": [{"name": "main", "image": "${{ secrets.AWS_ECR_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_NAME }}:${{ secrets.AWS_ECR_TAG1 }}", "essential": true, "memory": 1024, "portMappings": [{"hostPort": 8080, "containerPort": 8080}], "links": ["redis"]}, {"name": "redis", "image": "${{ secrets.AWS_ECR_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_NAME }}:${{ secrets.AWS_ECR_TAG2 }}", "essential": true, "memory": 1024, "portMappings": [{"hostPort": 6379, "containerPort": 6379}]}' > Dockerrun.aws.json

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Line-Up
          environment_name: line-up-env
          version_label: ${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: Dockerrun.aws.json