name: gcp-cd.yml
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Image using Docker Compose
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          KAKAO_ID: ${{ secrets.KAKAO_ID }}
          KAKAO_SECRET: ${{ secrets.KAKAO_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_S3_BUCKET_ACCESS_KEY: ${{ secrets.AWS_S3_BUCKET_ACCESS_KEY }}
          AWS_S3_BUCKET_SECRET_KEY: ${{ secrets.AWS_S3_BUCKET_SECRET_KEY }}
          FE_URL: ${{ secrets.FE_URL }}
          BE_URL: ${{ secrets.BE_URL }}
          QR_KEY: ${{ secrets.QR_KEY }}
        run: |
          docker-compose build
          docker tag main:latest ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:main
          docker tag redis:latest ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:redis
          docker tag nginx:latest ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:main
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:redis
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:nginx

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 35.216.82.11
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:nginx      
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:redis
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:main
            sudo docker-compose up -d
